#!/usr/bin/env bash
#Write a Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.

C=0

while [$C -lt 10 ]
do
	if [ $C -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	((C++))
done

